name: build

on:
  push:
    branches:
      - master
      - 'renovate/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2.4.2
      - name: Set up Node.js 14
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # tag=v2.5.1
        with:
          node-version: 14
      - run: yarn install
      - run: yarn build
