name: build

on:
  push:
    branches:
      - master
      - 'renovate/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Node.js 14
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
      - run: yarn install
      - run: yarn build
